### ISSUE TITLE
Create viewing dashboard

### ISSUE THREAD

**Issue by ayush-goyal** [HackGT/timber#31]
Under the epicenter tab, create a dashboard view similar to the screenshot below. It should display each project, and for each project, there should be a table for each category the project submitted for. Then, it should include each judges name, along with the total score they gave. This way, we can reference this and see what scores judges gave at a quick glance.

It might be helpful to use these components
- https://ant.design/components/table/
- https://ant.design/components/collapse/

![Screen Shot 2021-10-04 at 1 41 34 AM](https://user-images.githubusercontent.com/8273038/135799725-c92f230e-79d3-43ae-99ac-0b3d3a290cd9.png)
e

**Comment by mxinburritos** [comment]
<img width="1440" alt="Screen Shot 2021-10-04 at 7 08 38 PM" src="https://user-images.githubusercontent.com/25470781/135936399-dac4e69d-ee6f-4368-aaff-8c1694afb820.png">
Here's my implementation of the table

**Comment by mxinburritos** [comment]
<img width="1440" alt="Screen Shot 2021-10-04 at 7 09 55 PM" src="https://user-images.githubusercontent.com/25470781/135936492-c6710264-7bdb-4b38-9ecd-6d9dc03444e1.png">
Here's my implementation of the table!
